### ISSUE TITLE
Add OSS License check to build pipeline

### ISSUE THREAD

**Issue by ElinSwedin** [sebgroup/Spark-packages#181]
Add OSS License check to build pipeline.
Some licenses are not permitted for use in SEB.
We should investigate if we can add a license check in our build pipeline

**Comment by believer** [comment]
@ElinSwedin which licenses are permitted?

**Comment by ElinSwedin** [comment]
@believer I haven't investigated this further, just moved this ticket from our Neo-board. But I'll try to find out during the day and add more info to this ticket

**Comment by believer** [comment]
I've added [`check-licenses`](https://github.com/sebgroup/Spark-packages/blob/main/tools/check-licenses.mjs) that runs in the pipeline. We can update that script and the packages with the allowed licenses.

**Comment by believer** [comment]
All of the public repositories, that have been recently updated, in `sebgroup` use `Apache-2.0` as their license. I've changed all `package.json`s, included the license file in each `npm` release, and updated the new package generator to include a license file.
